### ISSUE TITLE
Shapes example in readme does not work

### ISSUE THREAD

**Issue by ingrinder** [Jollywatt/typst-fletcher#10]
The xkcd example demonstrating shapes appears at first not to work:
![image](https://github.com/Jollywatt/typst-fletcher/assets/12384431/3ce5368a-f171-46c8-a457-2a7e0400dd78)

However it seems e.g. `node-stroke: 1pt` is missing as this fixes the issue:
![image](https://github.com/Jollywatt/typst-fletcher/assets/12384431/f9ac9df2-49f5-4595-bb45-02905f3b98f0)

**Comment by Jollywatt** [comment]
Good catch, fixed in 4063d289cb9e8c46f69067ebcd6d1778b8301be4.

The code for the README examples were actually white lies — there's some extra code to make different versions of the diagrams for both light and dark modes. But I hide that code in the README itself to not be distracting. You spotted some code that got hidden when it shouldn't have!
