### ISSUE TITLE
More fine grained control of symbol in node

### ISSUE THREAD

**Issue by moritzketzer** [Jollywatt/typst-fletcher#33]
Hi,

Thanks again for the great work and your help :)

I have the following issue:

When I put a subscript of a symbol then it get's displaced from it's center.
However, I would like the symbol to remain in the center.
The align function does not help me here.
Is there another way to shift the 1 back to it's original center position, as it would be placed without the subscript?

![CleanShot 2024-05-15 at 12 17 40@2x](https://github.com/Jollywatt/typst-fletcher/assets/48527611/7c5e0caf-39f6-431d-9f8f-f5c4b10e0104)

**Comment by Jollywatt** [comment]
If you're talking about vertical alignment, try using block math instead of inline math (i.e., `$ 1_1 $` not `$1_1$`), and maybe adjust the `fit` parameter for the triangle (something like `shape: triangle.with(fit: 0.6)`).

If you're talking about horizontal alignment, try wrapping the label in `move()`.

P.S., the Typst discord channel has a more active community for questions like this which might be more appropriate than Github issues :)

**Comment by moritzketzer** [comment]
Ah thanks, and sorry, I will ask there :)
